name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t fluid-app:latest ./app

    - name: Verify Kubernetes Files
      run: |
        ls -l k8s
        cat k8s/app-deployment.yaml
